### PR TITLE
Add a return value section for jadoc

### PR DESCRIPTION
**Pull request by titsuki**
Hi.
I have updated Japanese document.

### CODE REVIEW

**Comment by lizmat** [comment]
hankache: I'm inclined to just merge it, would that have been ok?

**Comment by hankache** [comment]
@lizmat yes dear.  
@titsuki thanks.

**Comment by hankache** [comment]
@titsuki do you prefer to continue sending PRs or should I add you as collaborator so you can commit directly?

**Comment by titsuki** [comment]
@hankache
If you don't mind let me be a collaborator, I'll join :)

**Comment by titsuki** [comment]
@hankache 
Thanks a lot !

**Pull request merged**
