### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by garu**
Hi @hankache! First of all, THANK YOU for creating this very nice tutorial.

I went ahead and created a portuguese translation of it. As requested, it was translated directly against the english version and matches the current HEAD (7985e16).

I updated the README file to contain the new translation (with the pt.perl6intro.com link, which of course doesn't work yet).

Hope it helps :D

### CODE REVIEW

**Comment by hankache** [comment]
Hi @garu ! I am glad that you enjoyed the Perl 6 introduction. Thank you for creating the Portuguese translation.

I will host it on pt.perl6intro.com.

Meanwhile, if we can make some adjustments that would be great:
1- I usually add the translator as author. Can you provide me with an email I can put on the page?
2- I also usually assign the translator as a collaborator so they can manage their translation easily. Would you like this to happen?
3- The special blocks name should not be translated, because these are keywords that asciidoctor uses to generate special paragraphs:

* NOTE
* TIP
* WARNING

**Comment by garu** [comment]
@hankache hey! glad you're online, maybe we can do this now real quick :D 

1- sure! garu@cpan.org should do just fine, I guess :)
2- sure! I'd be honored.
3- no problem, let me do this right now real quick. One question, though: I see "NOTE:" and "[NOTE]". Should I restore both?

**Comment by garu** [comment]
(Same for TIP and WARNING, actually. There is "TIP:", "[TIP]", "WARNING:" and "[WARNING]". Which ones should I change?

**Comment by hankache** [comment]
@garu yes both forms with the colon and surrounded by brackets.

**Comment by garu** [comment]
@hankache done in commit 8082f3d! Maybe it's worth noting, I have also translated `.Output`. Is this something I should restore too?

**Comment by hankache** [comment]
@garu no just the ones I listed.

**Comment by garu** [comment]
Yay! Thanks!

**Comment by hankache** [comment]
@garu I am making the latest modifications. Will take it live in 5 min.

**Comment by hankache** [comment]
@garu http://pt.perl6intro.com is now live!

Well done!

**Comment by garu** [comment]
Yay! It looks awesome, @hankache - thanks! Hope this new translation we'll get us featured again on Perl 6 Weekly :D

**Comment by lizmat** [comment]
Pretty sure it will  :-)

**Pull request merged**
