### PR TITLE
Add a Japanese document

### PR DESCRIPTION
**Pull request by titsuki**
Hi
I translated the document in Japanese.
I'm good at Japanese, but not at adoc format.
So I might have some misunderstanding of this format.

### CODE REVIEW

**Comment by titsuki** [comment]
Sorry I'll fix many syntax errors soon.

**Comment by hankache** [comment]
@titsuki Great job!!  
If you need help with adoc ping me.  
Whenever you feel confident to publish the Japanese translation, inform me so I can merge the PR.

**Comment by titsuki** [comment]
Thanks for reply !
I have fixed many syntactic errors and I'm ready to merge this PR.

**Comment by titsuki** [comment]
Sorry, I found a typo and have fixed it. (above commit)

**Comment by titsuki** [comment]
I found that "code object" intend to imply "instance of the Code class". (See the above commit)
Is my understanding of this correct? If my understanding is wrong, I'll fix it again.

**Pull request merged**
