### PR TITLE
Improved instructions about installing on Linux

### PR DESCRIPTION
**Pull request by kberov**
Installing Rakudo Star manually was a simpler way for me.
Your mileage may vary.

### CODE REVIEW

**Comment by lizmat** [comment]
Please don't combine these into a single Pull Request.  The second commit is not covered by the title of the Pull Request.  Please make a separate pull request for that.

This is different for your own translation work: since our knowledge of Bulgarian is nil, we have to depend on your work anyway, so any PR for that we will merge, regardless of number of commits added.  :-)

**Comment by kberov** [comment]
Not sure what to do now.
Should I remove the second commit from this PR or change the title of the PR?
I realised the previous time that it is not good to mix improvements to the English version with the translation commits. 
Apologies.
That is why now I added only commits for the English version.
Please advise.
Regards

**Comment by lizmat** [comment]
I think the best thing would be to remove the second commit from this PR and create a new PR for it.

**Comment by kberov** [comment]
Regarding the translation I will have several reviews probably form other Bulgarians later.

**Comment by kberov** [comment]
Ok

**Comment by lizmat** [comment]
Having people review is good  :-)

**Comment by kberov** [comment]
done

**Comment by lizmat** [comment]
I like this change, FWIW.  But we would need to have this same change in all of the translations.  And we don't really have a protocol for notifying translators yet.  So I would like to hear Naoum's point of view on this before merging.

**Comment by kberov** [comment]
Ok, I understand.
I simply started watching the repository.
In one of my previous PR. I wrote why I deleted the copied version for translation.
Exactly for this reason - to not find my self translating outdated text.
Watching the repo is a good way to get notified about changes to the original document IMHO.

**Comment by kberov** [comment]
May be adding a note (similar to the above) to the "Translation" section in README.md will help.

**Comment by hankache** [comment]
OK for the change. We're recommending users to install Rakudo Star on Windows and OS X, I don't see why we shouldn't do the same for Linux.

Regarding translations, some translators watch the repo regularly and update their translation accordingly (hence the importance of clear PRs to the English version). Others don't and the only way to contact them is by email.

**Comment by hankache** [comment]
By the way, @kberov @lizmat thank you for the great work you're doing :)

**Comment by kberov** [comment]
Thanks!

**Pull request merged**
